name: Test module

on:
  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'README.md'
      - 'version.txt'
      - '.gitignore'
      - '.terraform-docs.yml'

# permissions:
#     contents: read

env:
  AWS_REGION: 'eu-central-1'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.8.1

      - name: Terraform test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform fmt -recursive -check
          terraform validate
          #terraform test -var-file=tests/test.tfvars
